name: healthch-core
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-dev
    environment:
      POSTGRES_USER: healthch-dev
      POSTGRES_PASSWORD: Changeme0
      POSTGRES_DB: healthch
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U healthch-dev -d healthch"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata: